@startuml

' documentation: https://plantuml.com/sequence-diagram

title Order sequence diagram

hide footbox
autonumber "<B>00"
skinparam roundcorner 20

actor "<B>Customer" as CUST

boundary "<B>Web\n<B>Application</B>" as WEB

participant OS [
    =OrderService
    ----
    Handles Order
    workflow
]

database "<B>MongoDB</B>" as DB

participant PS [
    =PaymentService
    ----
    Handles Credit Card
    Payments
]

participant CS [
    =CustomerService
    ----
    Handles Customer
    data
]

participant DS [
    =DeliveryService
    ----
    Handles Transport
    activities
]

participant KS [
    =KitchenService
    ----
    Handles Restaurant
    activities
]

entity "<B>Credit Card billing\n<B>[company]</B>" as CARD
entity "<B>Restaurant\n<B>[company]</B>" as CHEF
entity "<B>Transport\n<B>[company]</B>" as DELIVERY

CUST -> WEB: place order
activate WEB
WEB -> OS: /orders\n[POST]
activate OS
OS -> PS: /payments\n[POST]
activate PS
PS -> CS: /customers/xxx/billing\n[POST]
activate CS
CS --> PS: amount + billing data\n[response-status: 201]
deactivate CS
PS -> CARD: /billings\n[POST}
activate CARD
CARD --> PS: [response-status: 202]
PS -[#green]/ DB: Create payment
PS --> OS: [response-status: 202]
deactivate PS
OS -[#green]/ DB: Add order
OS --> WEB: [response-status: 202]
deactivate OS
deactivate WEB

note over CARD
Billing usually takes
      5-20 seconds
end note

CARD -[#blue]/ PS: status: paid\n[POST callback]
activate PS
PS -[#green]/ DB: Read payment

alt #LightBlue caller_id not found
    PS --> CARD: [response-status: 404]
else caller_id exists
    PS -[#green]/ DB: Update payment
    PS --[#red]/ OS: payment status\n[RabbitMQ wire protocol]
    activate OS
    PS --> CARD: [response-status: 201]
    deactivate CARD
    deactivate PS
end

OS -[#green]/ DB: Update order
OS -> DS: /deliveries\n[POST]
activate DS
DS -> CS: /customers/xxx/address\n[GET]
activate CS
CS --> DS: customer address\n[response-status: 200]
deactivate CS
DS -> DELIVERY: /delivery-request\n[POST]
activate DELIVERY
DELIVERY --> DS: status: deliveryScheduled\n[response-status: 202]
DS --> OS: delivery status\n[response-status: 202]
deactivate DS
OS -[#green]/ DB: Update order
deactivate OS

note over DELIVERY
Finding an available driver takes
an unknown number of minutes,
     but mostly 5-10 minutes.
end note

|||

alt #LightYellow Cancel current Order
    CUST -> WEB: cancel order
    activate WEB
    WEB -> OS: /orders/xxx/cancel\n[POST]
    activate OS
    OS -> DS: /deliveries/xxx/cancel\n[POST]
    activate DS
    DS -> DELIVERY: /delivery-request/xxx/cancel\n[PUT]
    DELIVERY --> DS: status: deliveryCancelled\n[response-status: 201]
    deactivate DELIVERY
    DS --> OS: [response-status: 201]
    deactivate DS
    OS -[#green]/ DB: Update order
    OS --> WEB: [response-status: 202]
    deactivate WEB

    OS -> PS: /payment/xxx/reimburse\n[POST]
    activate PS
    PS -> CS: /customers/xxx/billing\n[POST]
    activate CS
    CS --> PS: amount + billing data\n[response-status: 201]
    deactivate CS
    PS -> CARD: /billings/reimburse\n[POST]
    activate CARD
    CARD --> PS: [response-status: 202]
    PS --> OS: [response-status: 202]
    deactivate PS
    deactivate OS

    note over CARD
    Reimbursement usually
      takes 5-20 seconds.
    end note

    CARD -[#blue]/ PS: status: paid\n[POST callback]
    activate PS
    PS -[#green]/ DB: Read payment

    alt #LightBlue caller_id not found
        PS --> CARD: [response-status: 404]
    else caller_id exists
        PS -[#green]/ DB: Update payment
        PS --[#red]/ OS: payment status\n[RabbitMQ wire protocol]
        activate OS
        PS --> CARD: [response-status: 201]
        deactivate CARD
        deactivate PS
    end

    OS -[#green]/ DB: Update order
    deactivate OS

else continue waiting for an available driver
    activate DELIVERY
    DELIVERY -[#blue]/ DS: status:driverAvailable\n[POST callback]
    activate DS
    DS --[#red]/ OS: delivery status\n[RabbitMQ wire protocol]
    activate OS
    DS --> DELIVERY: [response-status: 201]
    deactivate DS
    OS -[#green]/ DB: Update order
    OS -> KS: /kitchen\n[POST]
    activate KS
    KS -> CHEF: /cooking-request\n[POST]
    activate CHEF
    CHEF --> KS: status: cookingScheduled\n[response-status: 202]
    KS --> OS: kitchen status\n[response-status: 201]
    deactivate KS
    OS -[#green]/ DB: Update order
    deactivate OS

    note over CHEF
    Normally takes
      10-20 minutes
    end note

    CHEF -[#blue]/ KS: status: cookingMeal\n[POST callback]
    activate KS
    KS --[#red]/ OS: kitchen status\n[RabbitMQ wire protocol]
    activate OS
    KS --> CHEF: [response-status: 201]
    deactivate KS
    OS -[#green]/ DB: Update order
    deactivate OS

    CHEF -[#blue]/ KS: status: cookingDone\n[POST callback]
    activate KS
    KS --[#red]/ OS: kitchen status\n[RabbitMQ wire protocol]
    activate OS
        KS --> CHEF: [response-status: 201]
    deactivate KS
    OS -[#green]/ DB: Update order
    deactivate OS

    CHEF -[#blue]/ KS: status: pickedUp\n[POST callback]
    activate KS
    KS --[#red]/ OS: kitchen status\n[RabbitMQ wire protocol]
    activate OS
    KS --> CHEF: [response-status: 201]
    deactivate CHEF
    deactivate KS
    OS -[#green]/ DB: Update order
    deactivate OS

    note over DELIVERY
    Normally takes
      10-20 minutes
    end note

    DELIVERY -[#blue]/ DS: status: inTransit\n[POST callback]
    activate DS
    DS --[#red]/ OS: delivery status\n[RabbitMQ wire protocol]
    activate OS
    DS --> DELIVERY: [response-status: 201]
    deactivate DS
    OS -[#green]/ DB: Update order
    deactivate OS

    DELIVERY -[#blue]/ DS: status: delivered\n[POST callback]
    activate DS
    DS --[#red]/ OS: delivery status\n[RabbitMQ wire protocol]
    activate OS
    DS --> DELIVERY: [response-status: 201]
    deactivate DELIVERY
    deactivate DS
    OS -[#green]/ DB: Update order
    deactivate OS
end

@enduml
